### ISSUE TITLE
Works great outside of house, but causes LAN issues.

### ISSUE THREAD

**Issue by stayupthetree** [origamiofficial/docker-ngrok-plex#2]
running the container replaces anything in the "Custom server access URLs" section with the ngrok IP and port, which also erases my custom one for LAN access "http://192.168.1.4:32400".

I set "PLEX_BaseURL='http://192.168.1.4:32400'"

Which does work, but all LAN traffic is still treated as WAN, is there a way to keep my custom LAN URL whenever it gets set by ngrok-plex?

**Comment by origamiofficial** [comment]
There is no need to include the LAN IP (192.168.1.4) in the "Custom server access URLs." Plex will use GDM to automatically find servers on your local network unless you've turned that off. I suggest you check the following links for further reference:

* [Enable GDM](https://support.plex.tv/articles/200430283-network/#:~:text=Enable%20local%20network%20discovery%20(GDM)&text=This%20is%20used%20to%20allows,automatically%20on%20a%20local%20network.)
* [Ports need to allow](https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/)
* [Can't find server](https://support.plex.tv/articles/204604227-why-can-t-the-plex-app-find-or-connect-to-my-plex-media-server/)

**Comment by origamiofficial** [comment]
As there has been no response from @stayupthetree  and the container has been verified to work fine on all platforms, I am considering this issue as solved. Feel free to reopen if you need further assistance.
