### ISSUE TITLE
Volume of data

### ISSUE THREAD

**Issue by ks2018ks** [origamiofficial/docker-ngrok-plex#33]
How much data goes through ngrok for ngrok-docker--plex to work?  Is it basically the amount of data streamed from plex to the remote device?

I received notice from ngrok:
 "
_We will be enforcing our published outgoing bandwidth limits beginning on January 23, 2024. Our records indicate that the free account connected to this email has exceeded our outgoing bandwidth limit of 1GB per month, over the last 3 months.

Beginning on January 23, 2024, free accounts that transmit >1GB of data will be placed on hold until the next billing cycle (for free accounts, billing cycles are tied to calendar months)._ "

**Comment by origamiofficial** [comment]
> How much data goes through ngrok for ngrok-docker--plex to work? Is it basically the amount of data streamed from plex to the remote device?

Yes, it is the amount of data streamed from Plex to the remote device.

> I received notice from ngrok: " _We will be enforcing our published outgoing bandwidth limits beginning on January 23, 2024. Our records indicate that the free account connected to this email has exceeded our outgoing bandwidth limit of 1GB per month, over the last 3 months.
> 
> Beginning on January 23, 2024, free accounts that transmit >1GB of data will be placed on hold until the next billing cycle (for free accounts, billing cycles are tied to calendar months)._ "

Thanks for the heads-up! ngrok free accounts are [bandwidth-limited](https://github.com/origamiofficial/docker-ngrok-plex/issues/33) to 1GB per month. You need to have a Pay-as-you-go plan for this project, see pricing [here](https://ngrok.com/pricing).
