### ISSUE TITLE
Temporarily disable? 

### ISSUE THREAD

**Issue by ks2018ks** [origamiofficial/docker-ngrok-plex#34]
Is there a way to temporarily disable this?  e.g. if I switch between ISPs?

I currently have docker-ngrok-plex (and plex) installed on a Synology NAS (thanks to [this support](url)).

I have 2 ISPs : one through a 5G SIM which has CGNAT, the other over ADSL, without CGNAT.  If I swap to the one without CGNAT, I assume docker-ngrok-plex doesn't 'know' and still routes my Plex remote connections through the ngrok?

If I log into my NAS and simply 'Stop' the Docker container, will that stop the plex traffic going through ngrok?

**Comment by origamiofficial** [comment]
I'm closing this issue. If you need anything else, let me know.
