### ISSUE TITLE
Unable to connect. 

### ISSUE THREAD

**Issue by Ringthane83** [origamiofficial/docker-ngrok-plex#5]
Please see the log file below. This container was working fine until I attempted to use the docker gui's update feature to update this container. The script seems to be working correctly as it updates the IP in the Plex network section, but I am unable to ping the IP provided by ngrok, or access it via my browser.

Troubleshooting so far:
Deleted and re-downloaded container
Refreshed ngrok token
Ran container with root privilege (to ensure its not a permission error)
Created new mount point for the container (To ensure folder was not permission locked)

I am running the newest version of plex: 1.32.5.7328

My container settings are as such

PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG: C.UTF-8
GPG_KEY: A035C8C19219BA821ECEA86B64E628F8D684696D
PYTHON_VERSION: 3.11.4
PYTHON_PIP_VERSION: 23.1.2
PYTHON_SETUPTOOLS_VERSION: 65.5.1
PYTHON_GET_PIP_URL: https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get-pip.py
PYTHON_GET_PIP_SHA256: 96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207
PLEX_BaseURL: http://192.168.40.147:32400
PLEX_Token: xxxx
NGROK_Token: xxxx

---Log---

<html><body>

date | stream | content
-- | -- | --
2023/07/24 18:16:57 | stdout | AttributeError: 'NoneType' object has no attribute 'split'
2023/07/24 18:16:57 | stdout | ^^^^^^^^^^^^^^
2023/07/24 18:16:57 | stdout | ngrokurlclean= ngrokurl.split('//')[-1]
2023/07/24 18:16:57 | stdout | File "/root/./ngrok-plex.py", line 41, in <module>
2023/07/24 18:16:57 | stdout | Traceback (most recent call last):
2023/07/24 18:16:52 | stdout | [?1049h[22;0;0t[?1h=[?25l[H[2JWaiting 5 seconds for ngrok to start up
2023/07/24 18:16:52 | stdout | Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
2023/07/24 18:08:38 | stdout | New settings: http://18.204.152.241:16423
2023/07/24 18:08:38 | stdout | Old settings: http://18.204.152.241:15500
2023/07/24 18:08:38 | stdout | ngrok url and ip no port = 18.204.152.241
2023/07/24 18:08:37 | stdout | ngrok base url = 2.tcp.ngrok.io
2023/07/24 18:08:32 | stdout | [?1049h[22;0;0t[?1h=[?25l[H[2JWaiting 5 seconds for ngrok to start up
2023/07/24 18:08:32 | stdout | Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
2023/07/24 18:07:57 | stdout | New settings: http://18.204.152.241:15500
2023/07/24 18:07:57 | stdout | Old settings: http://18.204.152.241:16099
2023/07/24 18:07:57 | stdout | ngrok url and ip no port = 18.204.152.241
2023/07/24 18:07:56 | stdout | ngrok base url = 0.tcp.ngrok.io
2023/07/24 18:07:51 | stdout | [?1049h[22;0;0t[?1h=[?25l[H[2JWaiting 5 seconds for ngrok to start up
2023/07/24 18:07:50 | stdout | Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
2023/07/24 17:13:31 | stdout | New settings: http://18.204.152.241:16099
2023/07/24 17:13:30 | stdout | Old settings: http://18.204.152.241:16857,http://100.89.180.124:32400
2023/07/24 17:13:30 | stdout | ngrok url and ip no port = 18.204.152.241
2023/07/24 17:13:30 | stdout | ngrok base url = 6.tcp.ngrok.io
2023/07/24 17:13:25 | stdout | [?1049h[22;0;0t[?1h=[?25l[H[2JWaiting 5 seconds for ngrok to start up
2023/07/24 17:13:24 | stdout | Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml

</body>
</html>

**Comment by origamiofficial** [comment]
Pushed a new update please check & let me know. I'm closing this issue as of now, if the issue still exist feel free to reopen.

**Comment by Ringthane83** [comment]
The attribute error is resolved. However, I am still not able to use the image to connect to Plex remotely. 

When creating the container I fill out all the default environment variables (plex and ngrok token) and set the network to host instead of a docker bridge network. The IP successfully changes in the Custom server access URLs fields but I am not able to access the URL. The container is not run with executive privileges. 

I am at a loss as to where the issue could be. 

-- In Plex --
Secure connections are set to preferred.  
Strict TLS is not checked.
Treat WAN IP As LAN Bandwidth is on
Enable Relay is on
Webhooks is on

<html><body>
<h2>rlabinc-ngrok-plex-1</h2>


date | stream | content
-- | -- | --
2023/08/15 17:02:31 | stdout | New settings: http://18.204.152.241:11539
2023/08/15 17:02:30 | stdout | Old settings: http://18.204.152.241:18443
2023/08/15 17:02:30 | stdout | ngrok url and ip no port = 18.204.152.241
2023/08/15 17:02:30 | stdout | ngrok base url = 4.tcp.ngrok.io
2023/08/15 17:02:25 | stdout | [?1049h[22;0;0t[?1h=[?25l[H[2JWaiting 5 seconds for ngrok to start up
2023/08/15 17:02:24 | stdout | Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml


</body>
</html>

**Comment by rlabinc** [comment]
@Ringthane83  Disable relay and remove the container completely and try again. Other users got fixed their problem via this.

**Comment by Ringthane83** [comment]
Relay has been disabled and the issue is persisting. Container was deleted as was the image and reinstalled.

**Comment by Ringthane83** [comment]
Good Evening thank you both for your help. After further troubleshooting I have determined the issue lies with ngrok and my home network. Container works great!

**Comment by origamiofficial** [comment]
Welcome!!
